/**
 * Generates real, distinct testnet wallets and submits real `pay()` transactions
 * against the deployed restaurant contract. These are automated smoke-test
 * transactions, NOT real human testers — see docs/USER_RECRUITMENT.md, where
 * each row generated by this script is labeled "Automated test wallet".
 */
import {
  Keypair,
  Contract,
  TransactionBuilder,
  rpc,
  Address,
  nativeToScVal,
} from '@stellar/stellar-sdk';

const RPC_URL = 'https://soroban-testnet.stellar.org';
const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
const CONTRACT_ID = process.env.VITE_CONTRACT_ID || 'CCG66EK4ZNG4LPB565VWSUEFDXCZM5RRUONQF4YEUQ5U2V5CL6WE2MU7';
const TOKEN_ADDRESS = process.env.VITE_TOKEN_ADDRESS || 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';

const MENU_ITEMS = [
  { id: 1, name: 'Neural Link Gen-S', price: 5000000 },
  { id: 2, name: 'Quantum Watch', price: 12000000 },
  { id: 3, name: 'Holo-Glasses v4', price: 8500000 },
  { id: 4, name: 'Cyber Drone', price: 15000000 },
];

const server = new rpc.Server(RPC_URL);
const COUNT = parseInt(process.argv[2] || '9', 10);

async function pollTx(txHash) {
  for (let i = 0; i < 30; i++) {
    try {
      const tx = await server.getTransaction(txHash);
      if (tx.status === rpc.Api.GetTransactionStatus.SUCCESS) return tx;
      if (tx.status === rpc.Api.GetTransactionStatus.FAILED) {
        throw new Error('Tx failed: ' + JSON.stringify(tx.resultXdr || tx));
      }
    } catch (e) {
      if (e.message?.includes('Bad union switch')) return { status: 'SUCCESS' };
      if (e.message?.startsWith('Tx failed')) throw e;
    }
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error('Timed out waiting for tx ' + txHash);
}

async function runOne(index) {
  const item = MENU_ITEMS[index % MENU_ITEMS.length];
  const orderId = 1000 + index; // offset so these never collide with real users' order ids
  const customer = Keypair.random();

  await fetch(`https://horizon-testnet.stellar.org/friendbot?addr=${customer.publicKey()}`);
  for (let i = 0; i < 10; i++) {
    try {
      await server.getAccount(customer.publicKey());
      break;
    } catch {
      await new Promise((r) => setTimeout(r, 2000));
    }
  }

  const account = await server.getAccount(customer.publicKey());
  const tx = new TransactionBuilder(account, { fee: '10000', networkPassphrase: NETWORK_PASSPHRASE })
    .addOperation(
      new Contract(CONTRACT_ID).call(
        'pay',
        Address.fromString(customer.publicKey()).toScVal(),
        Address.fromString(TOKEN_ADDRESS).toScVal(),
        nativeToScVal(item.price, { type: 'i128' }),
        nativeToScVal(orderId, { type: 'u64' })
      )
    )
    .setTimeout(60)
    .build();

  const sim = await server.simulateTransaction(tx);
  if (sim.error) throw new Error(`Simulation failed for ${customer.publicKey()}: ${sim.error}`);
  const assembled = rpc.assembleTransaction(tx, sim).build();
  assembled.sign(customer);
  const sent = await server.sendTransaction(assembled);
  await pollTx(sent.hash);

  return {
    wallet: customer.publicKey(),
    item: item.name,
    price: item.price / 1_000_000,
    orderId,
    txHash: sent.hash,
  };
}

async function main() {
  const results = [];
  for (let i = 0; i < COUNT; i++) {
    process.stdout.write(`[${i + 1}/${COUNT}] `);
    try {
      const r = await runOne(i);
      console.log(`OK  wallet=${r.wallet.slice(0, 8)}... item=${r.item} tx=${r.txHash}`);
      results.push(r);
    } catch (e) {
      console.log(`FAIL ${e.message}`);
    }
  }
  console.log('\n--- Markdown rows ---');
  results.forEach((r, i) => {
    console.log(
      `| ${i + 2} | \`${r.wallet.slice(0, 4)}...${r.wallet.slice(-4)}\` | [${r.txHash.slice(0, 8)}...](https://stellar.expert/explorer/testnet/tx/${r.txHash}) | 2026-07-27 | Automated test wallet (script-generated, not a real human tester) — bought "${r.item}" for ${r.price.toFixed(2)} XLM. |`
    );
  });
}

main();
